# Generated by Django 3.0.5 on 2020-04-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anneeDebut', models.IntegerField()),
                ('anneeFin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClasse', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('AnneeScolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AnneeScolaire')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Images')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=30)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('tel', models.IntegerField()),
                ('nationnalite', models.CharField(max_length=100)),
                ('etatSante', models.CharField(max_length=80)),
                ('parcours', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve_has_Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Emploi_temps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heureDebut', models.TimeField()),
                ('heureFin', models.TimeField()),
                ('jours', models.DateField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='etablissments')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=140)),
                ('tel', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('fax', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=85)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=80)),
                ('nom', models.CharField(max_length=80)),
                ('adresse', models.CharField(max_length=255)),
                ('cin', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=250)),
                ('civilite', models.CharField(max_length=5)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissance', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('etablissment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('capacite', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Batiment')),
            ],
        ),
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.TextField()),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Eleve')),
                ('emploitemps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Emploi_temps')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere_has_Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef', models.IntegerField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_niveaux', to='school.Matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveau_mats', to='school.Niveau')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Professeur'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='suivre',
            field=models.ManyToManyField(through='school.Matiere_has_Niveau', to='school.Niveau'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('duree', models.CharField(max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Matiere')),
                ('participants', models.ManyToManyField(through='school.Eleve_has_Evaluation', to='school.Eleve')),
            ],
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Matiere'),
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Professeur'),
        ),
        migrations.AddField(
            model_name='emploi_temps',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Salle'),
        ),
        migrations.AddField(
            model_name='eleve_has_evaluation',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_eleve', to='school.Evaluation'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Parent'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Niveau'),
        ),
        migrations.AddField(
            model_name='batiment',
            name='etablissment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Etablissement'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.TextField()),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Eleve')),
                ('emploitemps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Emploi_temps')),
                ('prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Professeur')),
            ],
        ),
    ]
